name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: football-app/package-lock.json

      - name: Install Expo workspace dependencies
        working-directory: football-app/football-app-expo
        run: npm install

      - name: Install dependencies
        working-directory: football-app
        run: npm install

      - name: Run tests
        working-directory: football-app
        run: npm test

      - name: Export web bundle for hosting
        working-directory: football-app
        run: npm run deploy:web

      - name: Configure Firebase credentials
        run: |
          cat <<EOF > "${RUNNER_TEMP}/firebase-service-account.json"
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          EOF
          echo "GOOGLE_APPLICATION_CREDENTIALS=${RUNNER_TEMP}/firebase-service-account.json" >> "$GITHUB_ENV"

      - name: Verify Firebase token is configured
        if: ${{ !secrets.FIREBASE_TOKEN }}
        run: |
          echo '"FIREBASE_TOKEN" secret is missing. Generate one with "firebase login:ci" and add it in the repository settings to enable non-interactive Firebase authentication.' >&2
          exit 1

      - name: Deploy to Firebase Hosting
        working-directory: football-app
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ -z "$FIREBASE_TOKEN" ]; then
            echo "\"FIREBASE_TOKEN\" secret is missing. Add it in the repository settings to enable non-interactive Firebase authentication." >&2
            exit 1
          fi
          npm install --global firebase-tools
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
